### ISSUE TITLE
Error Deploying CF Template

### ISSUE THREAD

**Issue by stevesloka** [mweagle/SpartaApplication#1]
I've been playing around with Sparta and am running this sample app. I basically commented out all functions in `spartaLambdaData` except the first one (`appendS3Lambda`). 

When I deploy my CF template fails to deploy and rolls back. I get these errors in the CloudWatch logs. What stands out to me is the null region, but maybe that's nothing. 

I'm curious if you've run into this or have any other thoughts around how I could debug:

```
"Data": {
        "Error": {
            "message": "Access Denied",
            "code": "AccessDenied",
            "region": null,
            "time": "2016-04-20T18:55:11.063Z",
            "requestId": "4DE823135B4CCA87",
            "extendedRequestId": "MwuN0jP5kXIwc1Qgk7MwBi8zQdQqEfkZY3IPdRomaq+HzrVg5Q2iKm+TgWPJ0v2dBb4bExEP4Vo=",
            "statusCode": 403,
            "retryable": false,
            "retryDelay": 95.23651925846934
        }
    }
```

**Comment by mweagle** [comment]
Following up from private thread...

The failure source is the [CustomResource](https://github.com/mweagle/Sparta/blob/master/resources/provision/apigateway.js) responsible for provisioning the API Gateway entries. Now that CloudFormation [supports APIGateway](https://aws.amazon.com/about-aws/whats-new/2016/04/aws-cloudformation-adds-support-for-amazon-api-gateway-and-updated-resource-support/), I've started migrating the APIGateway provisioning to resource definitions. Will be fixed in next release.

**Comment by mweagle** [comment]
@stevesloka - This should be resolved with https://github.com/mweagle/Sparta/releases/tag/0.5.5.  In local testing both the SpartaApplication and the https://github.com/mweagle/SpartaHTML applications successfully provision the APIGateway resources.

**Comment by mweagle** [comment]
Closing per private thread. @stevesloka please reopen/create a new issue if you're running into issues.
